import type { Metadata } from 'next';
import { siteContent } from '../site-content';
import { LegalShell } from '../legal-shell';
import { socialMetadata } from '../social-metadata';

export const dynamic = 'force-static';
export const metadata: Metadata = {
  title: 'Privacidad y cookies', description: 'Cómo trata innure tus consultas y cómo elegir la medición publicitaria.',
  ...socialMetadata('privacidad/', 'Privacidad y cookies | innure', 'Cómo trata innure tus consultas y cómo elegir la medición publicitaria.', siteContent.brand.domain),
  robots: { index: false, follow: true },
  alternates: { canonical: siteContent.brand.domain + 'privacidad/' },
};

export default function PrivacyPage() {
  const { legal, contact, advertising } = siteContent;
  return <LegalShell title="Privacidad y cookies">
    <section className="legal-section"><h2>1. Responsable</h2><p>{legal.companyName}, NIF {legal.taxId}, con domicilio en {legal.registeredAddress}. Para cuestiones de privacidad: <a href="mailto:info@innure.es">info@innure.es</a>.</p></section>
    <section className="legal-section"><h2>2. Datos y finalidad</h2><p>Esta política se aplica a todo innure.es, incluida la línea de pruebas de rendimiento en <a href="/rendimiento/">/rendimiento/</a>. Tratamos el nombre, empresa, correo, teléfono opcional y descripción del problema o del sistema que nos facilitas en cualquiera de los formularios para responder a tu consulta, hablar contigo y, en su caso, preparar una propuesta. No incluyas datos confidenciales ni información de terceras personas que no sea necesaria.</p>
      <p>El formulario de rendimiento adjunta a la consulta datos técnicos y de procedencia del envío: dirección IP, país aproximado, navegador, idioma, página de procedencia e identificadores de campaña presentes en la dirección de entrada. El formulario general solo añade esos identificadores de campaña si has aceptado la medición. No elaboramos perfiles ni tomamos decisiones automatizadas con estos datos.</p>
      <p>{contact.formEndpoint ? 'El formulario envía la consulta al correo de innure mediante una conexión cifrada. El servidor confirma el envío cuando el servicio de correo lo acepta; no guarda una base de datos de los mensajes en esta web.' : 'En esta vista de revisión, el formulario prepara un borrador en tu aplicación de correo. Solo nos llegará si decides enviarlo desde allí.'}</p>
      <p>Los servicios de alojamiento y seguridad pueden tratar datos técnicos de conexión, como IP y navegador. Para limitar abusos, el receptor mantiene contadores temporales y hashes, sin guardar en ellos el contenido del mensaje. La cuota se reinicia a los diez minutos y los registros caducados se descartan al atender nuevas solicitudes.</p>
    </section>
    <section className="legal-section"><h2>3. Base jurídica y conservación</h2><p>Respondemos a tu solicitud sobre la base de las medidas precontractuales que nos pides y, cuando corresponde, del consentimiento que prestas. La protección del formulario responde al interés legítimo de mantener un servicio seguro. La medición publicitaria es opcional y requiere tu consentimiento independiente.</p><p>{legal.retentionPeriod} Los datos no se utilizan para campañas de correo no solicitadas ni para tomar decisiones automatizadas sobre ti.</p></section>
    <section className="legal-section"><h2>4. Proveedores</h2><p>Para prestar el servicio intervienen DonDominio (Soluciones Corporativas IP, S.L.U.) en el alojamiento y el transporte del correo; Cloudflare, Inc. en la entrega, seguridad, protección antispam Turnstile y, en la línea de rendimiento, una analítica agregada de visitas sin cookies (Cloudflare Web Analytics); y los servicios de correo de Google (Google Ireland Ltd.) en el envío de algunas consultas y en el buzón operativo de respaldo. La consulta se dirige al buzón corporativo y a una copia operativa privada para reducir el riesgo de pérdida.</p><p>Si aceptas la medición, interviene también Google Ireland Ltd. No vendemos tus datos. Cuando un proveedor trata datos fuera del Espacio Económico Europeo, son aplicables los mecanismos y garantías de transferencia previstos por la normativa, que puedes consultar en la información de privacidad del proveedor o solicitar a innure.</p></section>
    <section className="legal-section" id="medicion"><h2>5. Cookies y medición opcional</h2>
      {advertising.conversionDestination ? <><p>Google Ads solo se carga si aceptas la medición. Relaciona el anuncio con un formulario cuyo envío haya sido aceptado. Se comunica una referencia aleatoria del envío, no tu nombre, correo, teléfono, empresa ni el texto de la consulta. No usamos remarketing, personalización publicitaria ni conversiones mejoradas.</p><p>En la línea de rendimiento, y también solo con tu permiso, se registran como señales auxiliares los clics hacia la sección de contacto, el inicio del formulario, sus errores y los clics en el correo electrónico. No incluyen lo que escribes, no cuentan como contactos y no se usan para optimizar las pujas.</p><p>Con tu permiso pueden conservarse identificadores de clic y datos de campaña presentes en la dirección de entrada. Las cookies de atribución de Google, que comienzan por <code>innure_auto_gcl_</code> o <code>_gcl_</code>, tienen habitualmente una duración de hasta 90 días. Los datos de campaña se limitan a la sesión y se descartan para la atribución después de 24 horas.</p><p>Tu elección se aplica en todo innure.es y se guarda en el navegador hasta 180 días. Puedes rechazar sin perder el acceso a los formularios y cambiarla cuando quieras desde «Configurar medición» en el pie o en esta página. Al rechazar o retirar el consentimiento se detiene la carga de las etiquetas y se eliminan las cookies de atribución de innure.es y los datos locales de atribución.</p></> : <p>Esta versión no carga Google Ads ni cookies de medición publicitaria. El formulario utiliza Turnstile para prevenir envíos automatizados; esta comprobación es independiente de la publicidad.</p>}
      <p>Sin necesidad de consentimiento, el navegador guarda también tu elección de medición y, al enviar el formulario de rendimiento, una copia temporal de lo escrito en la pestaña abierta para no perderlo si el envío falla; esa copia se borra al volver a cargar la página o al cerrar la pestaña.</p>
      <p>Más información: <a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noreferrer">privacidad de Cloudflare</a> y <a href="https://policies.google.com/privacy?hl=es" target="_blank" rel="noreferrer">privacidad de Google</a>.</p>
    </section>
    <section className="legal-section"><h2>6. Tus derechos</h2><p>Puedes solicitar acceso, rectificación, supresión, oposición, limitación o portabilidad de tus datos, y retirar el consentimiento, escribiendo a <a href="mailto:info@innure.es">info@innure.es</a>. La retirada no afecta a los tratamientos lícitos anteriores.</p><p>Si consideras que el tratamiento no respeta tus derechos, puedes reclamar ante la <a href="https://www.aepd.es/" target="_blank" rel="noreferrer">Agencia Española de Protección de Datos</a>.</p></section>
    <section className="legal-section"><h2>7. Seguridad</h2><p>Aplicamos medidas técnicas y organizativas adecuadas al riesgo para evitar la pérdida, el acceso no autorizado o la alteración de los datos. La comunicación con el sitio se realiza mediante conexión cifrada (HTTPS).</p></section>
    <section className="legal-section"><h2>8. Cambios</h2><p>Esta información se actualizará cuando cambien los tratamientos o el funcionamiento del sitio. La fecha de esta página identifica la versión vigente.</p></section>
  </LegalShell>;
}
